
package eu.rcware.dev.esgdb;

import org.datacontract.schemas._2004._07.esg_db_server.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HistoryDbAccess", targetNamespace = "http://dev.rcware.eu/esgdb")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    eu.rcware.dev.esgdb.ObjectFactory.class,
    ObjectFactory.class
})
public interface HistoryDbAccess {


    /**
     * 
     * @param credentials
     * @param records
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "SaveData", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/SaveData")
    @WebResult(name = "SaveDataResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "SaveData", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.SaveData")
    @ResponseWrapper(localName = "SaveDataResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.SaveDataResponse")
    public Integer saveData(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "records", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfValueRecord records);

    /**
     * 
     * @param variables
     * @param credentials
     * @return
     *     returns org.datacontract.schemas._2004._07.esg_db_server.EnsureVariablesResult
     */
    @WebMethod(operationName = "EnsureVariables", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/EnsureVariables")
    @WebResult(name = "EnsureVariablesResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "EnsureVariables", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.EnsureVariables")
    @ResponseWrapper(localName = "EnsureVariablesResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.EnsureVariablesResponse")
    public EnsureVariablesResult ensureVariables(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variables", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfVariableDescription variables);

    /**
     * 
     * @param valueCount
     * @param utcFrom
     * @param returnCode
     * @param credentials
     * @param nextVariableOffset
     * @param nextValueOffset
     * @param variableCount
     * @param utcTo
     * @param getDataResult
     * @param variablesKey
     * @param valueOffset
     * @param variableOffset
     */
    @WebMethod(operationName = "GetData", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetData")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetDataResponse")
    public void getData(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variablesKey", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variablesKey,
        @WebParam(name = "utcFrom", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar utcFrom,
        @WebParam(name = "utcTo", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar utcTo,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount,
        @WebParam(name = "valueOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer valueOffset,
        @WebParam(name = "valueCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer valueCount,
        @WebParam(name = "GetDataResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfMvr> getDataResult,
        @WebParam(name = "nextVariableOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextVariableOffset,
        @WebParam(name = "nextValueOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextValueOffset,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param valueCount
     * @param utcFrom
     * @param variableKeys
     * @param credentials
     * @param variableCount
     * @param utcTo
     * @param valueOffset
     * @param variableOffset
     * @return
     *     returns org.datacontract.schemas._2004._07.esg_db_server.GetDataAsyncResult
     */
    @WebMethod(operationName = "GetDataAsync", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetDataAsync")
    @WebResult(name = "GetDataAsyncResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "GetDataAsync", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetDataAsync")
    @ResponseWrapper(localName = "GetDataAsyncResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetDataAsyncResponse")
    public GetDataAsyncResult getDataAsync(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "utcFrom", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar utcFrom,
        @WebParam(name = "utcTo", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar utcTo,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount,
        @WebParam(name = "valueOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer valueOffset,
        @WebParam(name = "valueCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer valueCount);

    /**
     * 
     * @param returnCode
     * @param variableKeys
     * @param referenceTime
     * @param credentials
     * @param nextVariableOffset
     * @param dataSpecification
     * @param variableCount
     * @param getParticularDataResult
     * @param variableOffset
     */
    @WebMethod(operationName = "GetParticularData", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetParticularData")
    @RequestWrapper(localName = "GetParticularData", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetParticularData")
    @ResponseWrapper(localName = "GetParticularDataResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetParticularDataResponse")
    public void getParticularData(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "referenceTime", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar referenceTime,
        @WebParam(name = "dataSpecification", targetNamespace = "http://dev.rcware.eu/esgdb")
        ParticularDataSpecification dataSpecification,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount,
        @WebParam(name = "GetParticularDataResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfMvr> getParticularDataResult,
        @WebParam(name = "nextVariableOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextVariableOffset,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param variableKeys
     * @param referenceTime
     * @param credentials
     * @param dataSpecification
     * @param variableCount
     * @param variableOffset
     * @return
     *     returns org.datacontract.schemas._2004._07.esg_db_server.GetParticularDataAsyncResult
     */
    @WebMethod(operationName = "GetParticularDataAsync", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetParticularDataAsync")
    @WebResult(name = "GetParticularDataAsyncResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "GetParticularDataAsync", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetParticularDataAsync")
    @ResponseWrapper(localName = "GetParticularDataAsyncResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetParticularDataAsyncResponse")
    public GetParticularDataAsyncResult getParticularDataAsync(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "referenceTime", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar referenceTime,
        @WebParam(name = "dataSpecification", targetNamespace = "http://dev.rcware.eu/esgdb")
        ParticularDataSpecification dataSpecification,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount);

    /**
     * 
     * @param getTransformedDataResult
     * @param request
     * @param returnCode
     * @param variableKeys
     * @param intervalOffset
     * @param credentials
     * @param nextVariableOffset
     * @param intervalCount
     * @param variableCount
     * @param nextIntervalOffset
     * @param variableOffset
     */
    @WebMethod(operationName = "GetTransformedData", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetTransformedData")
    @RequestWrapper(localName = "GetTransformedData", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetTransformedData")
    @ResponseWrapper(localName = "GetTransformedDataResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetTransformedDataResponse")
    public void getTransformedData(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "request", targetNamespace = "http://dev.rcware.eu/esgdb")
        AggregationRequest request,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount,
        @WebParam(name = "intervalOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer intervalOffset,
        @WebParam(name = "intervalCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer intervalCount,
        @WebParam(name = "GetTransformedDataResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfVAg> getTransformedDataResult,
        @WebParam(name = "nextVariableOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextVariableOffset,
        @WebParam(name = "nextIntervalOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextIntervalOffset,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param request
     * @param variableKeys
     * @param intervalOffset
     * @param credentials
     * @param intervalCount
     * @param variableCount
     * @param variableOffset
     * @return
     *     returns org.datacontract.schemas._2004._07.esg_db_server.GetTransformedDataAsyncResult
     */
    @WebMethod(operationName = "GetTransformedDataAsync", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetTransformedDataAsync")
    @WebResult(name = "GetTransformedDataAsyncResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "GetTransformedDataAsync", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetTransformedDataAsync")
    @ResponseWrapper(localName = "GetTransformedDataAsyncResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetTransformedDataAsyncResponse")
    public GetTransformedDataAsyncResult getTransformedDataAsync(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "request", targetNamespace = "http://dev.rcware.eu/esgdb")
        AggregationRequest request,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "variableOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableOffset,
        @WebParam(name = "variableCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer variableCount,
        @WebParam(name = "intervalOffset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer intervalOffset,
        @WebParam(name = "intervalCount", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer intervalCount);

    /**
     * 
     * @param credentials
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CheckCredentials", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/CheckCredentials")
    @WebResult(name = "CheckCredentialsResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "CheckCredentials", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.CheckCredentials")
    @ResponseWrapper(localName = "CheckCredentialsResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.CheckCredentialsResponse")
    public Boolean checkCredentials(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ServerAlive", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/ServerAlive")
    @WebResult(name = "ServerAliveResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "ServerAlive", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.ServerAlive")
    @ResponseWrapper(localName = "ServerAliveResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.ServerAliveResponse")
    public Boolean serverAlive();

    /**
     * 
     * @param offset
     * @param moreDataAvailable
     * @param credentials
     * @param count
     * @param getAllVariablesResult
     */
    @WebMethod(operationName = "GetAllVariables", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetAllVariables")
    @RequestWrapper(localName = "GetAllVariables", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetAllVariables")
    @ResponseWrapper(localName = "GetAllVariablesResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetAllVariablesResponse")
    public void getAllVariables(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "offset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer offset,
        @WebParam(name = "count", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer count,
        @WebParam(name = "GetAllVariablesResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfVariableDescription> getAllVariablesResult,
        @WebParam(name = "moreDataAvailable", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Boolean> moreDataAvailable);

    /**
     * 
     * @param returnCode
     * @param variableKeys
     * @param getVariablesResult
     * @param offset
     * @param credentials
     * @param count
     * @param nextOffset
     */
    @WebMethod(operationName = "GetVariables", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetVariables")
    @RequestWrapper(localName = "GetVariables", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariables")
    @ResponseWrapper(localName = "GetVariablesResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariablesResponse")
    public void getVariables(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "offset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer offset,
        @WebParam(name = "count", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer count,
        @WebParam(name = "GetVariablesResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfVariableDescription> getVariablesResult,
        @WebParam(name = "nextOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextOffset,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param returnCode
     * @param variableKeys
     * @param offset
     * @param credentials
     * @param count
     * @param getVariableStatsResult
     * @param nextOffset
     */
    @WebMethod(operationName = "GetVariableStats", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetVariableStats")
    @RequestWrapper(localName = "GetVariableStats", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariableStats")
    @ResponseWrapper(localName = "GetVariableStatsResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariableStatsResponse")
    public void getVariableStats(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "offset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer offset,
        @WebParam(name = "count", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer count,
        @WebParam(name = "GetVariableStatsResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<ArrayOfVariableStatistics> getVariableStatsResult,
        @WebParam(name = "nextOffset", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> nextOffset,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param variableKeys
     * @param offset
     * @param credentials
     * @param count
     * @return
     *     returns org.datacontract.schemas._2004._07.esg_db_server.GetVariableStatsAsyncResult
     */
    @WebMethod(operationName = "GetVariableStatsAsync", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetVariableStatsAsync")
    @WebResult(name = "GetVariableStatsAsyncResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "GetVariableStatsAsync", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariableStatsAsync")
    @ResponseWrapper(localName = "GetVariableStatsAsyncResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetVariableStatsAsyncResponse")
    public GetVariableStatsAsyncResult getVariableStatsAsync(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "offset", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer offset,
        @WebParam(name = "count", targetNamespace = "http://dev.rcware.eu/esgdb")
        Integer count);

    /**
     * 
     * @param returnCode
     * @param variableKeys
     * @param credentials
     * @param from
     * @param to
     * @param deleteDataResult
     */
    @WebMethod(operationName = "DeleteData", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/DeleteData")
    @RequestWrapper(localName = "DeleteData", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.DeleteData")
    @ResponseWrapper(localName = "DeleteDataResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.DeleteDataResponse")
    public void deleteData(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "from", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://dev.rcware.eu/esgdb")
        XMLGregorianCalendar to,
        @WebParam(name = "DeleteDataResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> deleteDataResult,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @param returnCode
     * @param variableKeys
     * @param credentials
     * @param deleteVariablesResult
     */
    @WebMethod(operationName = "DeleteVariables", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/DeleteVariables")
    @RequestWrapper(localName = "DeleteVariables", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.DeleteVariables")
    @ResponseWrapper(localName = "DeleteVariablesResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.DeleteVariablesResponse")
    public void deleteVariables(
        @WebParam(name = "credentials", targetNamespace = "http://dev.rcware.eu/esgdb")
        Credentials credentials,
        @WebParam(name = "variableKeys", targetNamespace = "http://dev.rcware.eu/esgdb")
        ArrayOfArrayOfKeyValuePair variableKeys,
        @WebParam(name = "DeleteVariablesResult", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<Integer> deleteVariablesResult,
        @WebParam(name = "returnCode", targetNamespace = "http://dev.rcware.eu/esgdb", mode = WebParam.Mode.OUT)
        Holder<String> returnCode);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetServerVersion", action = "http://dev.rcware.eu/esgdb/HistoryDbAccess/GetServerVersion")
    @WebResult(name = "GetServerVersionResult", targetNamespace = "http://dev.rcware.eu/esgdb")
    @RequestWrapper(localName = "GetServerVersion", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetServerVersion")
    @ResponseWrapper(localName = "GetServerVersionResponse", targetNamespace = "http://dev.rcware.eu/esgdb", className = "eu.rcware.dev.esgdb.GetServerVersionResponse")
    public Integer getServerVersion();

}
