version: "3"
services:
  springBootApp:
    image: databridge:latest
    container_name: databridge-postgres-app
    environment:
      - POSTGRES_HOST=databridge-postgres-db
    ports:
      - "8081:8081"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure

  postgresDb:
    image: postgres:13.2
    container_name: databridge-postgres-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=eman_postgres_db

networks:
  network:

volumes:
  volume: