version: "3"
services:
  databridgeApp:
    image: databridge:latest
    container_name: databridge-postgres-app
    environment:
      - POSTGRES_HOST=databridge-postgres-db
    ports:
      - "8081:8081"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure

#  emanApp:
#    image: eman:latest
#    container_name: eman-postgres-app
#    environment:
#      - POSTGRES_HOST=postgresDb
#    ports:
#      - "8082:8082"
#    networks:
#      - network
#    restart: on-failure

  postgresDb:
    image: postgres:13.2
    container_name: databridge-postgres-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=eman_postgres_db

networks:
  network:

volumes:
  volume:
  pgdata: