postgres:
  host: ${POSTGRES_HOST:localhost:5434}
  
spring:
  datasource:
    url: jdbc:postgresql://${postgres.host}/eman_postgres_db?currentSchema=public&useSSL=false
    username: postgres
    password: root

  logging:
    level:
      org:
        springframework: DEBUG

server:
  error:
    include-message: always
  port: 8081

unipi:
  username: unipi_02819
  password:
  mervisUrl: http://db.unipi.technology/dbaccess